version: "3.9"
services:
  bank:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:4
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 1
      start_period: 5s
